.PHONY: clean All

All:
	@echo "----------Building project:[ TWOWSimulator - Debug ]----------"
	@cd "TWOWSimulator" && "$(MAKE)" -f  "TWOWSimulator.mk"
clean:
	@echo "----------Cleaning project:[ TWOWSimulator - Debug ]----------"
	@cd "TWOWSimulator" && "$(MAKE)" -f  "TWOWSimulator.mk" clean
